-- =============================================================================
-- Consolidated migration (module bundle): 0004_billing_returns_stock_links.sql
-- Sources merged in order (do not reorder):
--   25_create_bills_and_bill_items.sql
--   26_create_bill_returns_and_triggers.sql
--   27_users_allow_authenticated_read_own_row.sql
--   28_suppress_stock_adjustment_trigger_for_billing_and_others.sql
--   29_add_stock_transactions_for_bill_returns.sql
-- =============================================================================


-- >>> begin: 25_create_bills_and_bill_items.sql
/* =============================================================================
   MODULE — BILLING (BILLS & BILL ITEMS)
   Migration: bills, bill_items tables with bill number generation and
   automatic inventory deduction via existing reduce_product_stock.

   - bills:         main bill header (customer, amounts, payment, status)
   - bill_items:    line items per bill with product snapshots
   - Bill number:   B-YYYYMMDD-XXX (auto-generated, daily sequence)
   - Inventory:     on bill_items INSERT, reduce products.stock_quantity and
                    insert SALE into stock_transactions (uses reduce_product_stock)

   NOTE: bills.id is UUID (not BIGSERIAL) so stock_transactions.reference_id
   and reduce_product_stock(p_bill_id uuid) can reference it. bill_number is
   the human-readable business key (B-YYYYMMDD-XXX).
   Bill number is generated from existing rows (count of bills today + 1); no
   extra table.
   ============================================================================= */

/* -----------------------------------------------------------------------------
   STEP 1: CREATE bills TABLE (IF NOT EXISTS for idempotent re-run)
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bills (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_number            text,
  customer_id            uuid,
  subtotal_amount        numeric(18, 2) NOT NULL DEFAULT 0,
  other_items_amount     numeric(18, 2) NOT NULL DEFAULT 0,
  discount_type          text CHECK (discount_type IN ('AMOUNT', 'PERCENT')),
  discount_value         numeric(18, 2),
  discount_amount        numeric(18, 2) NOT NULL DEFAULT 0,
  total_payable_amount   numeric(18, 2) NOT NULL DEFAULT 0,
  payment_mode           text NOT NULL CHECK (payment_mode IN ('Cash', 'UPI', 'Card', 'Mixed')),
  cash_amount            numeric(18, 2) NOT NULL DEFAULT 0,
  online_amount          numeric(18, 2) NOT NULL DEFAULT 0,
  received_amount_total numeric(18, 2) NOT NULL DEFAULT 0,
  status                 text NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'RETURNED')),
  return_note            text,
  returned_at            timestamptz,
  created_by_user_id     uuid,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_bills_bill_number UNIQUE (bill_number),
  CONSTRAINT fk_bills_customer
    FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_bills_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.bills IS 'POS bill headers: amounts, payment, status. bill_number is human-readable (B-YYYYMMDD-XXX).';
COMMENT ON COLUMN public.bills.id IS 'Primary key (UUID for compatibility with stock_transactions.reference_id and reduce_product_stock).';
COMMENT ON COLUMN public.bills.bill_number IS 'Human-readable bill number; format B-YYYYMMDD-XXX, generated by trigger.';
COMMENT ON COLUMN public.bills.customer_id IS 'Optional; null for walk-in customers.';
COMMENT ON COLUMN public.bills.subtotal_amount IS 'Sum of all bill_items line totals before extra items or discounts.';
COMMENT ON COLUMN public.bills.other_items_amount IS 'Additional manual amount added to the bill.';
COMMENT ON COLUMN public.bills.discount_type IS 'AMOUNT = fixed discount, PERCENT = percentage off.';
COMMENT ON COLUMN public.bills.discount_value IS 'Raw value entered (currency for AMOUNT, percentage for PERCENT).';
COMMENT ON COLUMN public.bills.discount_amount IS 'Final calculated discount in currency.';
COMMENT ON COLUMN public.bills.total_payable_amount IS 'Final amount customer must pay (after discount and extra items).';
COMMENT ON COLUMN public.bills.payment_mode IS 'Cash, UPI, Card, or Mixed.';
COMMENT ON COLUMN public.bills.cash_amount IS 'Amount received in cash.';
COMMENT ON COLUMN public.bills.online_amount IS 'Amount received via UPI/card/digital.';
COMMENT ON COLUMN public.bills.received_amount_total IS 'Total received from customer.';
COMMENT ON COLUMN public.bills.status IS 'PENDING, PARTIALLY_PAID, PAID, or RETURNED.';
COMMENT ON COLUMN public.bills.return_note IS 'Optional note when bill is returned.';
COMMENT ON COLUMN public.bills.returned_at IS 'Timestamp when bill was returned.';
COMMENT ON COLUMN public.bills.created_by_user_id IS 'User who created the bill.';

CREATE INDEX IF NOT EXISTS idx_bills_bill_number ON public.bills(bill_number);
CREATE INDEX IF NOT EXISTS idx_bills_customer_id ON public.bills(customer_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_created_at ON public.bills(created_at);
CREATE INDEX IF NOT EXISTS idx_bills_created_by_user_id ON public.bills(created_by_user_id);

DROP TRIGGER IF EXISTS trigger_update_bills_updated_at ON public.bills;
CREATE TRIGGER trigger_update_bills_updated_at
  BEFORE UPDATE ON public.bills
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

/* -----------------------------------------------------------------------------
   STEP 2: CREATE bill_items TABLE (IF NOT EXISTS for idempotent re-run)
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bill_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_id       uuid NOT NULL,
  product_id   uuid NOT NULL,
  product_name text NOT NULL,
  barcode      text,
  unit_price   numeric(18, 2) NOT NULL,
  quantity     numeric(18, 3) NOT NULL,
  row_total    numeric(18, 2) NOT NULL,

  CONSTRAINT chk_bill_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT chk_bill_items_row_total_non_negative CHECK (row_total >= 0),
  CONSTRAINT fk_bill_items_bill
    FOREIGN KEY (bill_id) REFERENCES public.bills(id) ON DELETE CASCADE,
  CONSTRAINT fk_bill_items_product
    FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT
);

COMMENT ON TABLE public.bill_items IS 'Line items per bill; product name and barcode stored for historical accuracy.';
COMMENT ON COLUMN public.bill_items.product_name IS 'Snapshot of product name at time of billing.';
COMMENT ON COLUMN public.bill_items.barcode IS 'Snapshot of product barcode at time of billing.';
COMMENT ON COLUMN public.bill_items.unit_price IS 'Selling price per unit at time of billing.';
COMMENT ON COLUMN public.bill_items.row_total IS 'unit_price × quantity.';

CREATE INDEX IF NOT EXISTS idx_bill_items_bill_id ON public.bill_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_product_id ON public.bill_items(product_id);

/* -----------------------------------------------------------------------------
   STEP 4: Bill number generation — B-YYYYMMDD-XXX (no extra table)
   Uses COUNT of bills created today (created_at::date = CURRENT_DATE), then
   next sequence = count + 1. Advisory lock prevents duplicate numbers when
   multiple bills are created at the same time.
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.generate_bill_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_today     date := CURRENT_DATE;
  v_lock_key  bigint := to_char(v_today, 'YYYYMMDD')::bigint;
  v_count     integer;
  v_seq       integer;
BEGIN
  /* Do not overwrite if bill_number was provided */
  IF NEW.bill_number IS NOT NULL AND trim(NEW.bill_number) <> '' THEN
    RETURN NEW;
  END IF;

  /* Serialize per-day inserts so two concurrent inserts get different sequences */
  PERFORM pg_advisory_xact_lock(v_lock_key);

  /* Count bills created today (this row is not inserted yet) */
  SELECT COUNT(*)::integer
    INTO v_count
    FROM public.bills
   WHERE created_at::date = v_today;

  v_seq := v_count + 1;
  NEW.bill_number := 'B-' || to_char(v_today, 'YYYYMMDD') || '-' || lpad(v_seq::text, 3, '0');
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.generate_bill_number() IS 'Trigger: sets bill_number to B-YYYYMMDD-XXX from count of bills today + 1. Uses advisory lock to prevent duplicates. Does not overwrite if bill_number is already set.';

DROP TRIGGER IF EXISTS trigger_bills_generate_bill_number ON public.bills;
CREATE TRIGGER trigger_bills_generate_bill_number
  BEFORE INSERT ON public.bills
  FOR EACH ROW
  WHEN (NEW.bill_number IS NULL OR NEW.bill_number = '')
  EXECUTE PROCEDURE public.generate_bill_number();

/* -----------------------------------------------------------------------------
   STEP 5: Inventory deduction on bill_items INSERT
   Uses existing reduce_product_stock(product_id, quantity, bill_id) so that
   products.stock_quantity is decreased and SALE is logged in stock_transactions.
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.trigger_bill_items_deduct_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM public.reduce_product_stock(
    NEW.product_id,
    NEW.quantity,
    NEW.bill_id
  );
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.trigger_bill_items_deduct_stock() IS 'After insert on bill_items: reduces product stock and logs SALE in stock_transactions via reduce_product_stock.';

DROP TRIGGER IF EXISTS trigger_bill_items_after_insert_deduct_stock ON public.bill_items;
CREATE TRIGGER trigger_bill_items_after_insert_deduct_stock
  AFTER INSERT ON public.bill_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.trigger_bill_items_deduct_stock();

/* -----------------------------------------------------------------------------
   STEP 6: Row Level Security (RLS) for bills and bill_items
   ----------------------------------------------------------------------------- */
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_items ENABLE ROW LEVEL SECURITY;

-- bills: read and insert for POS; update for payments and returns
DROP POLICY IF EXISTS "Authenticated users can read bills" ON public.bills;
CREATE POLICY "Authenticated users can read bills"
ON public.bills FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can insert bills" ON public.bills;
CREATE POLICY "Authenticated users can insert bills"
ON public.bills FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can update bills" ON public.bills;
CREATE POLICY "Authenticated users can update bills"
ON public.bills FOR UPDATE USING (auth.uid() IS NOT NULL);

-- bill_items: read and insert (trigger deducts stock)
DROP POLICY IF EXISTS "Authenticated users can read bill_items" ON public.bill_items;
CREATE POLICY "Authenticated users can read bill_items"
ON public.bill_items FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can insert bill_items" ON public.bill_items;
CREATE POLICY "Authenticated users can insert bill_items"
ON public.bill_items FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

/* -----------------------------------------------------------------------------
   BILL NUMBER GENERATION — DUPLICATE PREVENTION & PRODUCTION NOTES

   How duplicates are prevented:
   1. pg_advisory_xact_lock(v_lock_key) — all inserts for the same calendar day
      take the same lock (key = YYYYMMDD as integer). Only one insert at a time
      for that day can run the COUNT + assign sequence, so each gets a unique
      sequence (count+1). The lock is transaction-scoped and released at commit.
   2. UNIQUE (bill_number) on bills — database enforces uniqueness; any
      duplicate would raise a constraint violation.

   Production suggestions:
   - idx_bills_created_at on created_at helps range queries; the trigger's
     COUNT uses created_at::date = CURRENT_DATE (expression index on that
     cast is not allowed — cast depends on session timezone, not immutable).
   - For very high throughput (many bills per second), the per-day advisory lock
     serializes inserts for that day; consider connection pooling and short
     transactions to avoid long waits.
   - If you need bill numbers by timezone (e.g. store local date), use a
     session variable or pass the date; CURRENT_DATE uses the database
     timezone (typically UTC in Supabase).
   ----------------------------------------------------------------------------- */

-- <<< end: 25_create_bills_and_bill_items.sql

-- >>> begin: 26_create_bill_returns_and_triggers.sql
/* =============================================================================
   MODULE — BILL RETURNS & REFUNDS (PHASE 5)
   Migration: bill_returns, bill_return_items tables with stock restoration,
   return quantity validation, and bill status updates.

   - bill_returns:      return header (bill_id, return_number, amounts, refund method)
   - bill_return_items: line items per return
   - Stock:             on bill_return_items INSERT, restore products.stock_quantity
   - Validation:        prevent returning more than sold per bill_item
   - Bill update:       update bills.status, returned_at, return_note on return
   ============================================================================= */

/* -----------------------------------------------------------------------------
   STEP 1: Add PARTIAL_RETURN to bills.status (existing: PENDING, PARTIALLY_PAID, PAID, RETURNED)
   ----------------------------------------------------------------------------- */
ALTER TABLE public.bills
  DROP CONSTRAINT IF EXISTS bills_status_check;

ALTER TABLE public.bills
  ADD CONSTRAINT bills_status_check CHECK (
    status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'RETURNED', 'PARTIAL_RETURN')
  );

COMMENT ON COLUMN public.bills.status IS 'PENDING, PARTIALLY_PAID, PAID, RETURNED, or PARTIAL_RETURN.';

/* -----------------------------------------------------------------------------
   STEP 2: CREATE bill_returns TABLE
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bill_returns (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_id              uuid NOT NULL REFERENCES public.bills(id) ON DELETE CASCADE,
  return_number        varchar(50) UNIQUE NOT NULL,
  return_note          text,
  total_return_amount  numeric(18, 2) NOT NULL CHECK (total_return_amount >= 0),
  refund_method        text NOT NULL DEFAULT 'Cash'
    CHECK (refund_method IN ('Cash', 'UPI', 'Card', 'Mixed')),
  refund_status        varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (refund_status IN ('pending', 'refunded')),
  created_by           uuid NOT NULL REFERENCES public.users(id),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.bill_returns IS 'Return/refund records for bills.';
COMMENT ON COLUMN public.bill_returns.return_number IS 'Human-readable return number; format R-YYYYMMDD-XXX.';
COMMENT ON COLUMN public.bill_returns.total_return_amount IS 'Sum of returned line items.';
COMMENT ON COLUMN public.bill_returns.refund_method IS 'Cash, UPI, Card, or Mixed.';
COMMENT ON COLUMN public.bill_returns.refund_status IS 'pending or refunded.';

CREATE INDEX IF NOT EXISTS idx_bill_returns_bill_id ON public.bill_returns(bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_returns_created_at ON public.bill_returns(created_at);
CREATE INDEX IF NOT EXISTS idx_bill_returns_return_number ON public.bill_returns(return_number);

DROP TRIGGER IF EXISTS trigger_update_bill_returns_updated_at ON public.bill_returns;
CREATE TRIGGER trigger_update_bill_returns_updated_at
  BEFORE UPDATE ON public.bill_returns
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

/* -----------------------------------------------------------------------------
   STEP 3: Return number generation — R-YYYYMMDD-XXX (similar to bill_number)
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.generate_return_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_today     date := CURRENT_DATE;
  v_lock_key  bigint := 9000000000 + (to_char(v_today, 'YYYYMMDD')::bigint);
  v_count     integer;
  v_seq       integer;
BEGIN
  IF NEW.return_number IS NOT NULL AND trim(NEW.return_number) <> '' THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(v_lock_key);

  SELECT COUNT(*)::integer
    INTO v_count
    FROM public.bill_returns
   WHERE created_at::date = v_today;

  v_seq := v_count + 1;
  NEW.return_number := 'R-' || to_char(v_today, 'YYYYMMDD') || '-' || lpad(v_seq::text, 3, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_bill_returns_generate_return_number ON public.bill_returns;
CREATE TRIGGER trigger_bill_returns_generate_return_number
  BEFORE INSERT ON public.bill_returns
  FOR EACH ROW
  WHEN (NEW.return_number IS NULL OR NEW.return_number = '')
  EXECUTE PROCEDURE public.generate_return_number();

/* -----------------------------------------------------------------------------
   STEP 4: CREATE bill_return_items TABLE
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bill_return_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  return_id     uuid NOT NULL REFERENCES public.bill_returns(id) ON DELETE CASCADE,
  bill_item_id  uuid NOT NULL REFERENCES public.bill_items(id),
  product_id    uuid NOT NULL REFERENCES public.products(id),
  product_name  text NOT NULL,
  quantity      integer NOT NULL CHECK (quantity > 0),
  unit_price    numeric(18, 2) NOT NULL CHECK (unit_price >= 0),
  line_total    numeric(18, 2) NOT NULL CHECK (line_total >= 0),
  created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.bill_return_items IS 'Line items per bill return; stock is restored on insert.';

CREATE INDEX IF NOT EXISTS idx_bill_return_items_return_id ON public.bill_return_items(return_id);
CREATE INDEX IF NOT EXISTS idx_bill_return_items_bill_item_id ON public.bill_return_items(bill_item_id);
CREATE INDEX IF NOT EXISTS idx_bill_return_items_product_id ON public.bill_return_items(product_id);

/* -----------------------------------------------------------------------------
   STEP 5: Stock restoration trigger — increase stock when return items inserted
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.restore_product_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.products
  SET stock_quantity = stock_quantity + NEW.quantity
  WHERE id = NEW.product_id;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.restore_product_stock() IS 'After insert on bill_return_items: increases product stock.';

DROP TRIGGER IF EXISTS trg_restore_stock_after_return ON public.bill_return_items;
CREATE TRIGGER trg_restore_stock_after_return
  AFTER INSERT ON public.bill_return_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.restore_product_stock();

/* -----------------------------------------------------------------------------
   STEP 6: Prevent over-return — validate quantity <= (sold - already returned)
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.validate_return_quantity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  sold_qty     numeric;
  returned_qty integer;
BEGIN
  SELECT quantity INTO sold_qty
  FROM public.bill_items
  WHERE id = NEW.bill_item_id;

  IF sold_qty IS NULL THEN
    RAISE EXCEPTION 'Bill item not found';
  END IF;

  SELECT COALESCE(SUM(quantity), 0)::integer
  INTO returned_qty
  FROM public.bill_return_items
  WHERE bill_item_id = NEW.bill_item_id;

  IF returned_qty + NEW.quantity > sold_qty::integer THEN
    RAISE EXCEPTION 'Return quantity exceeds sold quantity for this item';
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.validate_return_quantity() IS 'Before insert on bill_return_items: ensures return qty <= sold qty - already returned.';

DROP TRIGGER IF EXISTS trg_validate_return_qty ON public.bill_return_items;
CREATE TRIGGER trg_validate_return_qty
  BEFORE INSERT ON public.bill_return_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.validate_return_quantity();

/* -----------------------------------------------------------------------------
   STEP 7: Row Level Security for bill_returns and bill_return_items
   ----------------------------------------------------------------------------- */
ALTER TABLE public.bill_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_return_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read bill_returns" ON public.bill_returns;
CREATE POLICY "Authenticated users can read bill_returns"
  ON public.bill_returns FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can insert bill_returns" ON public.bill_returns;
CREATE POLICY "Authenticated users can insert bill_returns"
  ON public.bill_returns FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can update bill_returns" ON public.bill_returns;
CREATE POLICY "Authenticated users can update bill_returns"
  ON public.bill_returns FOR UPDATE USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can read bill_return_items" ON public.bill_return_items;
CREATE POLICY "Authenticated users can read bill_return_items"
  ON public.bill_return_items FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can insert bill_return_items" ON public.bill_return_items;
CREATE POLICY "Authenticated users can insert bill_return_items"
  ON public.bill_return_items FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- <<< end: 26_create_bill_returns_and_triggers.sql

-- >>> begin: 27_users_allow_authenticated_read_own_row.sql
/* =============================================================================
   Ensure authenticated users can always read their own row from public.users.
   Fixes "User not found" when the row exists but role-based policies (get_my_role)
   or RLS edge cases prevent the select from returning the row.
   ============================================================================= */

-- Allow any authenticated user to read their own user row (id = auth.uid()).
-- This does not grant access to other users' rows; Admin/Manager policies still
-- control access to other rows.
CREATE POLICY "Authenticated read own user row"
ON public.users
FOR SELECT
USING (id = auth.uid());

-- <<< end: 27_users_allow_authenticated_read_own_row.sql

-- >>> begin: 28_suppress_stock_adjustment_trigger_for_billing_and_others.sql
/* =============================================================================
   MODULE — SUPPRESS STOCK ADJUSTMENT TRIGGER FOR BILLING / RETURNS / STOCK-IN

   When a bill is generated, reduce_product_stock() updates products.stock_quantity
   and then inserts a SALE row into stock_transactions. The trigger
   trg_products_stock_adjustment also fires on that UPDATE and inserts an
   ADJUSTMENT_OUT row, so we get two entries (SALE + ADJUSTMENT_OUT) per line.

   Same double-logging can occur for:
   - Stock-in (PURCHASE + ADJUSTMENT_IN)
   - Bill returns (restore_product_stock UPDATE → ADJUSTMENT_IN only, wrong ref)

   Fix: Use a transaction-local GUC so the adjustment trigger skips when the
   update is from reduce_product_stock, restore_product_stock, or create_stock_in.
   ============================================================================= */

/* -----------------------------------------------------------------------------
   STEP 1: log_product_stock_adjustment — skip when suppress flag is set
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.log_product_stock_adjustment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_old   numeric(18,3);
  v_new   numeric(18,3);
  v_diff  numeric(18,3);
  v_type  text;
BEGIN
  -- Skip when stock change is from billing, returns, or stock-in (they log their own transaction type)
  IF current_setting('app.suppress_stock_adjustment', true) = 'true' THEN
    RETURN NEW;
  END IF;

  v_old  := COALESCE(OLD.stock_quantity, 0);
  v_new  := COALESCE(NEW.stock_quantity, 0);
  v_diff := v_new - v_old;

  IF v_diff <> 0 THEN
    v_type := CASE WHEN v_diff > 0 THEN 'ADJUSTMENT_IN' ELSE 'ADJUSTMENT_OUT' END;

    INSERT INTO public.stock_transactions (
      product_id,
      transaction_type,
      quantity,
      reference_type,
      reference_id,
      notes
    )
    VALUES (
      NEW.id,
      v_type,
      v_diff,
      'PRODUCT_EDIT',
      NEW.id,
      'Stock adjusted via product edit'
    );
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.log_product_stock_adjustment() IS
  'Logs ADJUSTMENT_IN or ADJUSTMENT_OUT when products.stock_quantity changes on update. Skips when app.suppress_stock_adjustment is set (billing, returns, stock-in).';

/* -----------------------------------------------------------------------------
   STEP 2: reduce_product_stock — set flag before UPDATE so only SALE is logged
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.reduce_product_stock(
  p_product_id   uuid,
  p_quantity    numeric,
  p_bill_id     uuid
)
RETURNS boolean
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_updated integer;
BEGIN
  PERFORM set_config('app.suppress_stock_adjustment', 'true', true);

  UPDATE public.products
  SET stock_quantity = stock_quantity - p_quantity
  WHERE id = p_product_id
    AND stock_quantity >= p_quantity;

  GET DIAGNOSTICS v_updated = ROW_COUNT;

  IF v_updated = 0 THEN
    RAISE EXCEPTION 'Insufficient stock for product %', p_product_id;
  END IF;

  INSERT INTO public.stock_transactions (
    product_id,
    transaction_type,
    "quantity",
    reference_type,
    reference_id,
    notes
  )
  VALUES (
    p_product_id,
    'SALE',
    -p_quantity,
    'BILL',
    p_bill_id,
    'POS sale'
  );

  RETURN true;
END;
$fn$;

COMMENT ON FUNCTION public.reduce_product_stock(uuid, numeric, uuid) IS
  'Safely decreases product stock by p_quantity for billing; logs SALE stock_transaction. Raises if insufficient stock. Suppresses product adjustment trigger to avoid duplicate ADJUSTMENT_OUT.';

/* -----------------------------------------------------------------------------
   STEP 3: restore_product_stock — set flag before UPDATE (avoids wrong ADJUSTMENT_IN)
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.restore_product_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM set_config('app.suppress_stock_adjustment', 'true', true);

  UPDATE public.products
  SET stock_quantity = stock_quantity + NEW.quantity
  WHERE id = NEW.product_id;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.restore_product_stock() IS
  'After insert on bill_return_items: increases product stock. Suppresses adjustment trigger.';

/* -----------------------------------------------------------------------------
   STEP 4: create_stock_in — set flag before UPDATE so only PURCHASE is logged
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.create_stock_in(
  p_date           date,
  p_items          jsonb,
  p_supplier_id    uuid DEFAULT NULL,
  p_invoice_number text DEFAULT NULL,
  p_notes          text DEFAULT NULL,
  p_created_by     uuid DEFAULT NULL
)
RETURNS TABLE(id uuid)
LANGUAGE plpgsql
AS $$
DECLARE
  v_stock_in_id   uuid;
  v_item          jsonb;

  v_product_id         uuid;
  v_manufacturing_date date;
  v_quantity           numeric(18,3);
  v_row_total          numeric(18,2);

  v_total_items   integer        := 0;
  v_total_amount  numeric(18,2)  := 0;
BEGIN
  IF p_items IS NULL
     OR jsonb_typeof(p_items) <> 'array'
     OR jsonb_array_length(p_items) = 0
  THEN
    RAISE EXCEPTION 'p_items must be a non-empty JSON array of line items';
  END IF;

  FOR v_item IN
    SELECT value
    FROM jsonb_array_elements(p_items) AS t(value)
  LOOP
    v_quantity  := COALESCE((v_item->>'quantity')::numeric(18,3), 0);
    v_row_total := COALESCE((v_item->>'row_total')::numeric(18,2), 0);

    v_total_items  := v_total_items + 1;
    v_total_amount := v_total_amount + v_row_total;
  END LOOP;

  INSERT INTO public.stock_in (
    date,
    supplier_id,
    invoice_number,
    notes,
    total_items,
    total_amount,
    created_by
  )
  VALUES (
    p_date,
    p_supplier_id,
    p_invoice_number,
    p_notes,
    v_total_items,
    v_total_amount,
    p_created_by
  )
  RETURNING public.stock_in.id INTO v_stock_in_id;

  PERFORM set_config('app.suppress_stock_adjustment', 'true', true);

  FOR v_item IN
    SELECT value
    FROM jsonb_array_elements(p_items) AS t(value)
  LOOP
    v_product_id         := (v_item->>'product_id')::uuid;
    v_manufacturing_date  := (v_item->>'manufacturing_date')::date;
    v_quantity            := COALESCE((v_item->>'quantity')::numeric(18,3), 0);
    v_row_total           := COALESCE((v_item->>'row_total')::numeric(18,2), 0);

    INSERT INTO public.stock_in_items (
      stock_in_id,
      product_id,
      manufacturing_date,
      quantity,
      row_total
    )
    VALUES (
      v_stock_in_id,
      v_product_id,
      v_manufacturing_date,
      v_quantity,
      v_row_total
    );

    UPDATE public.products AS p
    SET stock_quantity = COALESCE(p.stock_quantity, 0) + v_quantity
    WHERE p.id = v_product_id;

    INSERT INTO public.stock_transactions (
      product_id,
      transaction_type,
      quantity,
      reference_type,
      reference_id,
      notes
    )
    VALUES (
      v_product_id,
      'PURCHASE',
      v_quantity,
      'STOCK_IN',
      v_stock_in_id,
      p_invoice_number
    );
  END LOOP;

  RETURN QUERY SELECT v_stock_in_id;
END;
$$;

COMMENT ON FUNCTION public.create_stock_in(
  date, jsonb, uuid, text, text, uuid
) IS
  'Creates a stock_in purchase entry with items, updates products.stock_quantity, and logs PURCHASE stock_transactions. Suppresses adjustment trigger to avoid duplicate ADJUSTMENT_IN.';

-- <<< end: 28_suppress_stock_adjustment_trigger_for_billing_and_others.sql

-- >>> begin: 29_add_stock_transactions_for_bill_returns.sql
/* =============================================================================
   MODULE — BILL RETURNS: LOG INTO stock_transactions

   Extends restore_product_stock() so that each return item also writes a
   RETURN_IN row into stock_transactions for a complete stock history.

   Tables involved:
   - bill_return_items: line items per bill return (NEW.return_id, NEW.product_id, NEW.quantity)
   - stock_transactions: unified stock movement history

   This migration is safe to run after:
   - 11_create_stock_in_and_transactions.sql   (creates stock_transactions)
   - 26_create_bill_returns_and_triggers.sql   (creates bill_return_items + initial restore_product_stock)
   - 28_suppress_stock_adjustment_trigger_for_billing_and_others.sql
     (redefines restore_product_stock to set suppress flag)
   ============================================================================= */

CREATE OR REPLACE FUNCTION public.restore_product_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Ensure generic adjustment trigger does not double-log ADJUSTMENT_IN
  PERFORM set_config('app.suppress_stock_adjustment', 'true', true);

  -- 1) Restore stock to products
  UPDATE public.products
  SET stock_quantity = stock_quantity + NEW.quantity
  WHERE id = NEW.product_id;

  -- 2) Log stock movement as RETURN_IN tied to this bill return
  INSERT INTO public.stock_transactions (
    product_id,
    transaction_type,
    quantity,
    reference_type,
    reference_id,
    notes
  )
  VALUES (
    NEW.product_id,
    'RETURN_IN',
    NEW.quantity,       -- positive: stock coming back to inventory
    'BILL_RETURN',
    NEW.return_id,      -- references bill_returns.id
    'Bill return'
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.restore_product_stock() IS
  'After insert on bill_return_items: increases product stock and logs RETURN_IN in stock_transactions. Suppresses adjustment trigger.';


-- <<< end: 29_add_stock_transactions_for_bill_returns.sql
