/* =============================================================================
   MODULE — BILLING (BILLS & BILL ITEMS)
   Migration: bills, bill_items tables with bill number generation and
   automatic inventory deduction via existing reduce_product_stock.

   - bills:         main bill header (customer, amounts, payment, status)
   - bill_items:    line items per bill with product snapshots
   - Bill number:   B-YYYYMMDD-XXX (auto-generated, daily sequence)
   - Inventory:     on bill_items INSERT, reduce products.stock_quantity and
                    insert SALE into stock_transactions (uses reduce_product_stock)

   NOTE: bills.id is UUID (not BIGSERIAL) so stock_transactions.reference_id
   and reduce_product_stock(p_bill_id uuid) can reference it. bill_number is
   the human-readable business key (B-YYYYMMDD-XXX).
   Bill number is generated from existing rows (count of bills today + 1); no
   extra table.
   ============================================================================= */

/* -----------------------------------------------------------------------------
   STEP 1: CREATE bills TABLE (IF NOT EXISTS for idempotent re-run)
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bills (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_number            text,
  customer_id            uuid,
  subtotal_amount        numeric(18, 2) NOT NULL DEFAULT 0,
  other_items_amount     numeric(18, 2) NOT NULL DEFAULT 0,
  discount_type          text CHECK (discount_type IN ('AMOUNT', 'PERCENT')),
  discount_value         numeric(18, 2),
  discount_amount        numeric(18, 2) NOT NULL DEFAULT 0,
  total_payable_amount   numeric(18, 2) NOT NULL DEFAULT 0,
  payment_mode           text NOT NULL CHECK (payment_mode IN ('Cash', 'UPI', 'Card', 'Mixed')),
  cash_amount            numeric(18, 2) NOT NULL DEFAULT 0,
  online_amount          numeric(18, 2) NOT NULL DEFAULT 0,
  received_amount_total numeric(18, 2) NOT NULL DEFAULT 0,
  status                 text NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'RETURNED')),
  return_note            text,
  returned_at            timestamptz,
  created_by_user_id     uuid,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_bills_bill_number UNIQUE (bill_number),
  CONSTRAINT fk_bills_customer
    FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_bills_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.bills IS 'POS bill headers: amounts, payment, status. bill_number is human-readable (B-YYYYMMDD-XXX).';
COMMENT ON COLUMN public.bills.id IS 'Primary key (UUID for compatibility with stock_transactions.reference_id and reduce_product_stock).';
COMMENT ON COLUMN public.bills.bill_number IS 'Human-readable bill number; format B-YYYYMMDD-XXX, generated by trigger.';
COMMENT ON COLUMN public.bills.customer_id IS 'Optional; null for walk-in customers.';
COMMENT ON COLUMN public.bills.subtotal_amount IS 'Sum of all bill_items line totals before extra items or discounts.';
COMMENT ON COLUMN public.bills.other_items_amount IS 'Additional manual amount added to the bill.';
COMMENT ON COLUMN public.bills.discount_type IS 'AMOUNT = fixed discount, PERCENT = percentage off.';
COMMENT ON COLUMN public.bills.discount_value IS 'Raw value entered (currency for AMOUNT, percentage for PERCENT).';
COMMENT ON COLUMN public.bills.discount_amount IS 'Final calculated discount in currency.';
COMMENT ON COLUMN public.bills.total_payable_amount IS 'Final amount customer must pay (after discount and extra items).';
COMMENT ON COLUMN public.bills.payment_mode IS 'Cash, UPI, Card, or Mixed.';
COMMENT ON COLUMN public.bills.cash_amount IS 'Amount received in cash.';
COMMENT ON COLUMN public.bills.online_amount IS 'Amount received via UPI/card/digital.';
COMMENT ON COLUMN public.bills.received_amount_total IS 'Total received from customer.';
COMMENT ON COLUMN public.bills.status IS 'PENDING, PARTIALLY_PAID, PAID, or RETURNED.';
COMMENT ON COLUMN public.bills.return_note IS 'Optional note when bill is returned.';
COMMENT ON COLUMN public.bills.returned_at IS 'Timestamp when bill was returned.';
COMMENT ON COLUMN public.bills.created_by_user_id IS 'User who created the bill.';

CREATE INDEX IF NOT EXISTS idx_bills_bill_number ON public.bills(bill_number);
CREATE INDEX IF NOT EXISTS idx_bills_customer_id ON public.bills(customer_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_created_at ON public.bills(created_at);
CREATE INDEX IF NOT EXISTS idx_bills_created_by_user_id ON public.bills(created_by_user_id);

DROP TRIGGER IF EXISTS trigger_update_bills_updated_at ON public.bills;
CREATE TRIGGER trigger_update_bills_updated_at
  BEFORE UPDATE ON public.bills
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

/* -----------------------------------------------------------------------------
   STEP 2: CREATE bill_items TABLE (IF NOT EXISTS for idempotent re-run)
   ----------------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS public.bill_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_id       uuid NOT NULL,
  product_id   uuid NOT NULL,
  product_name text NOT NULL,
  barcode      text,
  unit_price   numeric(18, 2) NOT NULL,
  quantity     numeric(18, 3) NOT NULL,
  row_total    numeric(18, 2) NOT NULL,

  CONSTRAINT chk_bill_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT chk_bill_items_row_total_non_negative CHECK (row_total >= 0),
  CONSTRAINT fk_bill_items_bill
    FOREIGN KEY (bill_id) REFERENCES public.bills(id) ON DELETE CASCADE,
  CONSTRAINT fk_bill_items_product
    FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT
);

COMMENT ON TABLE public.bill_items IS 'Line items per bill; product name and barcode stored for historical accuracy.';
COMMENT ON COLUMN public.bill_items.product_name IS 'Snapshot of product name at time of billing.';
COMMENT ON COLUMN public.bill_items.barcode IS 'Snapshot of product barcode at time of billing.';
COMMENT ON COLUMN public.bill_items.unit_price IS 'Selling price per unit at time of billing.';
COMMENT ON COLUMN public.bill_items.row_total IS 'unit_price × quantity.';

CREATE INDEX IF NOT EXISTS idx_bill_items_bill_id ON public.bill_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_product_id ON public.bill_items(product_id);

/* -----------------------------------------------------------------------------
   STEP 4: Bill number generation — B-YYYYMMDD-XXX (no extra table)
   Uses COUNT of bills created today (created_at::date = CURRENT_DATE), then
   next sequence = count + 1. Advisory lock prevents duplicate numbers when
   multiple bills are created at the same time.
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.generate_bill_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_today     date := CURRENT_DATE;
  v_lock_key  bigint := to_char(v_today, 'YYYYMMDD')::bigint;
  v_count     integer;
  v_seq       integer;
BEGIN
  /* Do not overwrite if bill_number was provided */
  IF NEW.bill_number IS NOT NULL AND trim(NEW.bill_number) <> '' THEN
    RETURN NEW;
  END IF;

  /* Serialize per-day inserts so two concurrent inserts get different sequences */
  PERFORM pg_advisory_xact_lock(v_lock_key);

  /* Count bills created today (this row is not inserted yet) */
  SELECT COUNT(*)::integer
    INTO v_count
    FROM public.bills
   WHERE created_at::date = v_today;

  v_seq := v_count + 1;
  NEW.bill_number := 'B-' || to_char(v_today, 'YYYYMMDD') || '-' || lpad(v_seq::text, 3, '0');
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.generate_bill_number() IS 'Trigger: sets bill_number to B-YYYYMMDD-XXX from count of bills today + 1. Uses advisory lock to prevent duplicates. Does not overwrite if bill_number is already set.';

DROP TRIGGER IF EXISTS trigger_bills_generate_bill_number ON public.bills;
CREATE TRIGGER trigger_bills_generate_bill_number
  BEFORE INSERT ON public.bills
  FOR EACH ROW
  WHEN (NEW.bill_number IS NULL OR NEW.bill_number = '')
  EXECUTE PROCEDURE public.generate_bill_number();

/* -----------------------------------------------------------------------------
   STEP 5: Inventory deduction on bill_items INSERT
   Uses existing reduce_product_stock(product_id, quantity, bill_id) so that
   products.stock_quantity is decreased and SALE is logged in stock_transactions.
   ----------------------------------------------------------------------------- */
CREATE OR REPLACE FUNCTION public.trigger_bill_items_deduct_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM public.reduce_product_stock(
    NEW.product_id,
    NEW.quantity,
    NEW.bill_id
  );
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.trigger_bill_items_deduct_stock() IS 'After insert on bill_items: reduces product stock and logs SALE in stock_transactions via reduce_product_stock.';

DROP TRIGGER IF EXISTS trigger_bill_items_after_insert_deduct_stock ON public.bill_items;
CREATE TRIGGER trigger_bill_items_after_insert_deduct_stock
  AFTER INSERT ON public.bill_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.trigger_bill_items_deduct_stock();

/* -----------------------------------------------------------------------------
   STEP 6: Row Level Security (RLS) for bills and bill_items
   ----------------------------------------------------------------------------- */
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_items ENABLE ROW LEVEL SECURITY;

-- bills: read and insert for POS; update for payments and returns
DROP POLICY IF EXISTS "Authenticated users can read bills" ON public.bills;
CREATE POLICY "Authenticated users can read bills"
ON public.bills FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can insert bills" ON public.bills;
CREATE POLICY "Authenticated users can insert bills"
ON public.bills FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can update bills" ON public.bills;
CREATE POLICY "Authenticated users can update bills"
ON public.bills FOR UPDATE USING (auth.uid() IS NOT NULL);

-- bill_items: read and insert (trigger deducts stock)
DROP POLICY IF EXISTS "Authenticated users can read bill_items" ON public.bill_items;
CREATE POLICY "Authenticated users can read bill_items"
ON public.bill_items FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Authenticated users can insert bill_items" ON public.bill_items;
CREATE POLICY "Authenticated users can insert bill_items"
ON public.bill_items FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

/* -----------------------------------------------------------------------------
   BILL NUMBER GENERATION — DUPLICATE PREVENTION & PRODUCTION NOTES

   How duplicates are prevented:
   1. pg_advisory_xact_lock(v_lock_key) — all inserts for the same calendar day
      take the same lock (key = YYYYMMDD as integer). Only one insert at a time
      for that day can run the COUNT + assign sequence, so each gets a unique
      sequence (count+1). The lock is transaction-scoped and released at commit.
   2. UNIQUE (bill_number) on bills — database enforces uniqueness; any
      duplicate would raise a constraint violation.

   Production suggestions:
   - idx_bills_created_at on created_at helps range queries; the trigger's
     COUNT uses created_at::date = CURRENT_DATE (expression index on that
     cast is not allowed — cast depends on session timezone, not immutable).
   - For very high throughput (many bills per second), the per-day advisory lock
     serializes inserts for that day; consider connection pooling and short
     transactions to avoid long waits.
   - If you need bill numbers by timezone (e.g. store local date), use a
     session variable or pass the date; CURRENT_DATE uses the database
     timezone (typically UTC in Supabase).
   ----------------------------------------------------------------------------- */
